import type { ConsoleFixture } from "./types";

// The built-in fallback rendered when neither the endpoint nor the bundled
// tree.json can be reached (FR-009-07). Minimal but complete: a root, one step,
// a two-branch fan-out, and a verdict.
export const SAMPLE: ConsoleFixture = {
  head: "b0",
  live_sandboxes: 0,
  session_elapsed: 0,
  runtime_version: "—",
  verdict: {
    winner: 0,
    reason: "branch b0 exited 0 with usable output; b1 hit AssertionError",
    provider: "deterministic-fallback",
  },
  nodes: [
    {
      id: "root",
      index: 0,
      instruction: "(start)",
      parent: null,
      children: ["s1"],
      sandbox: "sample-sandbox-0",
      state: "live",
      snapshot: "cp-sample0",
      created_at: "2026-08-29T00:00:00+00:00",
      exit_code: 0,
      stdout: "",
      outcome: "ok",
      terminal: null,
      rationale: "",
    },
    {
      id: "s1",
      index: 1,
      instruction: "echo 'def add(a,b): return a+b' > calc.py",
      parent: "root",
      children: ["s2"],
      sandbox: "sample-sandbox-0",
      state: "live",
      snapshot: "cp-sample1",
      created_at: "2026-08-29T00:00:05+00:00",
      exit_code: 0,
      stdout: "",
      outcome: "ok",
      terminal: null,
      rationale: "write the implementation first",
    },
    {
      id: "s2",
      index: 2,
      instruction:
        "python3 -c \"exec(open('calc.py').read()); assert add(2,2)==4; print('PASS')\"",
      parent: "s1",
      children: [],
      sandbox: "sample-sandbox-0",
      state: "live",
      snapshot: "cp-sample2",
      created_at: "2026-08-29T00:00:10+00:00",
      exit_code: 0,
      stdout: "PASS\n",
      outcome: "ok",
      terminal: null,
      rationale: "",
    },
    {
      id: "b0",
      index: 3,
      instruction: "echo 'def add(a,b): return a+b' > calc.py && python3 test.py",
      parent: "s1",
      children: [],
      sandbox: "sample-sandbox-1",
      state: "live",
      snapshot: null,
      created_at: "2026-08-29T00:00:12+00:00",
      exit_code: 0,
      stdout: "PASS\n",
      outcome: "ok",
      terminal: "done",
      rationale: "scripted candidate continuation",
      branch: true,
      progress: { state: "done", elapsed_seconds: 6.8 },
    },
    {
      id: "b1",
      index: 4,
      instruction: "echo 'def add(a,b): return a-b' > calc.py && python3 test.py",
      parent: "s1",
      children: [],
      sandbox: "sample-sandbox-2",
      state: "released",
      snapshot: null,
      created_at: "2026-08-29T00:00:12+00:00",
      exit_code: 1,
      stdout: "AssertionError\n",
      outcome: "failed",
      terminal: "failed",
      rationale: "scripted candidate continuation",
      branch: true,
      progress: { state: "failed", elapsed_seconds: 6.6 },
    },
  ],
};
