"""src/rewind/capabilities.py — the enforced sandbox capability contract.

At import, this module loads `.rewind/capability-map.toml` and validates it. Any
lifecycle operation the code declares that is not in that verified map, or any
incomplete map entry, raises `CapabilityError` — a subclass of `ImportError`, so
it fails when the code is loaded, not during a demo (spec FR-000-03, NFR-000-01).

Nothing here imports a vendor SDK. The map is generated by `tools/spine_test.py`
from a live account run; this module only reads and enforces it.
"""

from __future__ import annotations

import os
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Mapping

# --------------------------------------------------------------------------- errors


class CapabilityError(ImportError):
    """Raised at import time when the capability contract is violated."""


# ----------------------------------------------------------------------- map location


def _map_path() -> Path:
    override = os.environ.get("REWIND_CAPABILITY_MAP")
    if override:
        return Path(override)
    # src/rewind/capabilities.py -> repo root is two parents up from the package
    return Path(__file__).resolve().parents[2] / ".rewind" / "capability-map.toml"


# ----------------------------------------------------------------------- contract data


@dataclass(frozen=True)
class Contract:
    runtime_version: str
    account_cpu_total: int
    max_branches: int
    classes: frozenset[str]
    verified_ops: frozenset[str]
    class_of: Mapping[str, str] = field(default_factory=dict)
    post_condition: Mapping[str, str] = field(default_factory=dict)
    experimental: Mapping[str, str] = field(default_factory=dict)  # name -> marker


def load_and_validate(path: Path | str) -> Contract:
    """Pure loader — used at import with the default path and by unit tests with
    a temp file. Raises CapabilityError on anything wrong."""
    p = Path(path)
    try:
        raw = p.read_bytes()
    except OSError as e:
        raise CapabilityError(
            f"capability map unreadable at {p}: {e}. "
            f"Generate it with `python tools/spine_test.py`."
        ) from e
    if not raw.strip():
        raise CapabilityError(f"capability map is empty at {p}.")
    try:
        data = tomllib.loads(raw.decode("utf-8"))
    except (tomllib.TOMLDecodeError, UnicodeDecodeError) as e:
        raise CapabilityError(f"capability map at {p} is not valid TOML: {e}") from e

    for key in ("runtime_version", "account_cpu_total", "max_branches", "classes"):
        if key not in data:
            raise CapabilityError(f"capability map at {p} is missing top-level `{key}`.")

    classes = data["classes"]
    if not isinstance(classes, list) or not classes or not all(isinstance(c, str) for c in classes):
        raise CapabilityError(f"capability map at {p}: `classes` must be a non-empty list of strings.")
    classes_set = frozenset(classes)

    cpu = data["account_cpu_total"]
    if not isinstance(cpu, int) or cpu <= 0:
        raise CapabilityError(f"capability map at {p}: `account_cpu_total` must be a positive int.")

    max_branches = data["max_branches"]
    if not isinstance(max_branches, int) or not (0 < max_branches <= cpu):
        raise CapabilityError(
            f"capability map at {p}: `max_branches` must be an int in 1..{cpu}."
        )

    ops = data.get("operation")
    if not isinstance(ops, list) or not ops:
        raise CapabilityError(f"capability map at {p}: at least one `[[operation]]` is required.")

    verified: set[str] = set()
    class_of: dict[str, str] = {}
    post: dict[str, str] = {}
    experimental: dict[str, str] = {}

    for i, op in enumerate(ops):
        where = f"operation[{i}]"
        name = op.get("name")
        if not isinstance(name, str) or not name.strip():
            raise CapabilityError(f"{p}: {where} has no `name`.")
        if name in verified:
            raise CapabilityError(f"{p}: operation `{name}` declared twice.")

        rc = op.get("required_class")
        if rc not in classes_set:
            raise CapabilityError(
                f"{p}: operation `{name}` incomplete declaration — "
                f"`required_class` must be one of {sorted(classes_set)}, got {rc!r}."
            )

        pc = op.get("post_condition")
        if not isinstance(pc, str) or not pc.strip():
            raise CapabilityError(
                f"{p}: operation `{name}` incomplete declaration — "
                f"`post_condition` was not asserted."
            )

        is_exp = op.get("experimental")
        if not isinstance(is_exp, bool):
            raise CapabilityError(f"{p}: operation `{name}` must set `experimental` to true or false.")
        marker = op.get("experimental_marker")
        if is_exp:
            if not isinstance(marker, str) or not marker.strip():
                raise CapabilityError(
                    f"{p}: operation `{name}` is experimental but records no "
                    f"`experimental_marker` — incomplete declaration."
                )
            experimental[name] = marker
        elif marker:
            raise CapabilityError(
                f"{p}: operation `{name}` is not experimental but sets `experimental_marker`."
            )

        verified.add(name)
        class_of[name] = rc
        post[name] = pc

    return Contract(
        runtime_version=str(data["runtime_version"]),
        account_cpu_total=cpu,
        max_branches=max_branches,
        classes=classes_set,
        verified_ops=frozenset(verified),
        class_of=class_of,
        post_condition=post,
        experimental=experimental,
    )


# ------------------------------------------------------------------ load at import time

CONTRACT: Contract = load_and_validate(_map_path())

VERIFIED_OPS: frozenset[str] = CONTRACT.verified_ops
CLASS_OF: Mapping[str, str] = CONTRACT.class_of
POST_CONDITION: Mapping[str, str] = CONTRACT.post_condition
EXPERIMENTAL: Mapping[str, str] = CONTRACT.experimental
CEILING: int = CONTRACT.account_cpu_total
MAX_BRANCHES: int = CONTRACT.max_branches
RUNTIME_VERSION: str = CONTRACT.runtime_version


# -------------------------------------------------------------------- declared bounds
# Every wait and retry in the feature is a declared value, never an open loop
# (spec NFR-000-05). Values come from the recorded map timings; env overrides let
# a constrained venue lower them.


def _f(env: str, default: float) -> float:
    try:
        return float(os.environ[env])
    except (KeyError, ValueError):
        return default


def _i(env: str, default: int) -> int:
    try:
        return int(os.environ[env])
    except (KeyError, ValueError):
        return default


READINESS_WAIT: float = _f("REWIND_READINESS_WAIT", 30.0)   # cold-start command readiness
SLOT_WAIT: float = _f("REWIND_SLOT_WAIT", 20.0)             # wait for a ceiling slot
DESTROY_RETRIES: int = _i("REWIND_DESTROY_RETRIES", 3)
DESTROY_RETRY_GAP: float = _f("REWIND_DESTROY_RETRY_GAP", 2.0)
AUTO_STOP_MIN: int = _i("SANDBOX_AUTO_STOP_MINUTES", 2)
AUTO_DELETE_MIN: int = _i("SANDBOX_AUTO_DELETE_MINUTES", 10)
CRITIC_WAIT: float = _f("REWIND_CRITIC_WAIT", 8.0)          # spec 005 — bounded critic wall-clock
ALT_WAIT: float = min(_f("REWIND_ALT_WAIT", CRITIC_WAIT), CRITIC_WAIT)   # spec 008 — <= CRITIC_WAIT


# --------------------------------------------------------------------------- asserts


def assert_declared(ops: Iterable[str]) -> None:
    """Raise CapabilityError naming the first operation not in the verified map."""
    for op in ops:
        if op not in VERIFIED_OPS:
            raise CapabilityError(
                f"lifecycle operation {op!r} is not in the verified capability map "
                f"({_map_path()}); verified operations are {sorted(VERIFIED_OPS)}."
            )


def assert_class(op: str, handle) -> None:
    """Refuse an operation against a sandbox class that does not support it,
    before any runtime call (spec FR-000-04)."""
    if op not in VERIFIED_OPS:
        raise CapabilityError(f"operation {op!r} is not declared.")
    required = CLASS_OF[op]
    actual = getattr(handle, "sandbox_class", None)
    if actual is not None and actual != required:
        raise CapabilityError(
            f"operation {op!r} requires a {required!r} sandbox but the handle is {actual!r}."
        )
